# Maven
# Build and deploy Mule project and run tests with Apache Maven.

trigger:
- master

variables:
  - group: build.variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package deploy'
    options: '-DskipTests -Danypoint.username=$(anypointUsername) -Danypoint.password=$(anypointPassword) -DmuleDeploy -Pdev'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false